### Send POST request with json body
POST http://localhost:8080/tasks/
Content-Type: application/json

{
  "image": "creckx/testimage",
  "domains": ["localhost:8081"],
  "command": ["/srv/testtask"]
}

###

GET http://localhost:8080/tasks/
Content-Type: application/json

###

# Get by domain

GET http://localhost:8080/tasks/by-domain/localhost:8081
Content-Type: application/json

###

# Delete by UUID

DELETE http://localhost:8080/tasks/c7d45d0c-20ca-4e45-9512-2f7dcc46bb54

###