### Send POST request with json body
POST http://localhost:8080/tasks/
Content-Type: application/json

{
  "image": "creckx/testimage",
  "domains": ["localhost:8081"],
  "command": ["/srv/testtask"],
  "volume_type": "S3",
  "source": "testtask.zip"
}

###

GET http://localhost:8080/tasks/
Content-Type: application/json

###

# Get by domain

GET http://localhost:8080/tasks/by-domain/localhost:8081
Content-Type: application/json

###

# Delete by UUID

DELETE http://localhost:8080/tasks/faa4ccba914e4dc09b3a732ef76df951

###