### Send POST request with json body
POST http://localhost:1323/tasks/
Content-Type: application/json

{
  "image": "creckx/testimage",
  "domains": ["localhost:8081"],
  "command": ["/srv/testtask"]
}

###

GET http://localhost:1323/tasks/
Content-Type: application/json

###

# Get by domain

GET http://localhost:1323/tasks/by-domain/localhost:8080
Content-Type: application/json

###